# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
username "alpriest@gmail.com"
app_identifier "com.alpriest.EnergyStats"
ignore_language_directory_validation true
overwrite_screenshots true