//
//  SolarStringsSettingsView.swift
//  Energy Stats
//
//  Created by Alistair Priest on 27/02/2024.
//

import Energy_Stats_Core
import SwiftUI

struct SolarStringsSettingsView: View {
    @ObservedObject var viewModel: SettingsTabViewModel
    @State private var showStringSelection: Bool
    @State private var pv1 = false
    @State private var pv2 = false
    @State private var pv3 = false
    @State private var pv4 = false

    init(viewModel: SettingsTabViewModel) {
        self.viewModel = viewModel
        self._showStringSelection = State(wrappedValue: viewModel.showSeparateStringsOnPowerFlow)
        self._pv1 = State(wrappedValue: viewModel.enabledPowerFlowStrings.contains(.pv1))
        self._pv2 = State(wrappedValue: viewModel.enabledPowerFlowStrings.contains(.pv2))
        self._pv3 = State(wrappedValue: viewModel.enabledPowerFlowStrings.contains(.pv3))
        self._pv4 = State(wrappedValue: viewModel.enabledPowerFlowStrings.contains(.pv4))
    }

    var body: some View {
        Section {
            Toggle(isOn: $viewModel.showSeparateStringsOnPowerFlow) {
                Text("Show PV power by strings")
            }.onChange(of: viewModel.showSeparateStringsOnPowerFlow) { newValue in
                withAnimation {
                    showStringSelection = newValue
                }
            }

            if showStringSelection {
                VStack {
                    Toggle(isOn: $pv1) {
                        Text("PV1")
                    }
                    Toggle(isOn: $pv2) {
                        Text("PV2")
                    }
                    Toggle(isOn: $pv3) {
                        Text("PV3")
                    }
                    Toggle(isOn: $pv4) {
                        Text("PV4")
                    }
                }.onChange(of: pv1) {
                    toggle(string: .pv1, state: $0)
                }.onChange(of: pv2) {
                    toggle(string: .pv2, state: $0)
                }.onChange(of: pv3) {
                    toggle(string: .pv3, state: $0)
                }.onChange(of: pv4) {
                    toggle(string: .pv4, state: $0)
                }
            }
        } footer: {
            Text("If you have multiple sets of solar panels, e.g. front/rear of your home, this will let you see the power being generated by each set. Setting takes effect on next data fetch.")
        }
    }

    private func toggle(string: PowerFlowStrings, state: Bool) {
        if state {
            viewModel.enabledPowerFlowStrings.insert(string)
        } else {
            viewModel.enabledPowerFlowStrings.remove(string)
        }
    }
}

#if DEBUG
#Preview {
    SolarStringsSettingsView(viewModel: SettingsTabViewModel(
        userManager: .preview(),
        config: PreviewConfigManager(),
        networking: DemoNetworking())
    )
}
#endif
