//
//  VariableType.swift
//  Energy Stats
//
//  Created by Alistair Priest on 12/09/2022.
//

import SwiftUI

enum ReportVariable: String, RawRepresentable {
    case feedIn
    case generation
    case gridConsumption
    case chargeEnergyTotal
    case dischargeEnergyTotal
}

enum RawVariable: String, RawRepresentable {
    case generationPower
    case feedinPower
    case batChargePower
    case batDischargePower
    case gridConsumptionPower
    case loadsPower

    var title: String {
        switch self {
        case .generationPower:
            return "Output power"
        case .feedinPower:
            return "Feed-in power"
        case .batChargePower:
            return "Charge power"
        case .batDischargePower:
            return "Discharge power"
        case .gridConsumptionPower:
            return "Grid consumption power"
        case .loadsPower:
            return "Loads power"
        }
    }

    var networkTitle: String {
        self.rawValue
    }

    var colour: Color {
        switch self {
        case .batChargePower:
            return .green.opacity(0.8)
        case .batDischargePower:
            return .red.opacity(0.5)
        case .generationPower:
            return .yellow.opacity(0.8)
        case .gridConsumptionPower:
            return .red.opacity(0.8)
        case .feedinPower:
            return .mint.opacity(0.8)
        case .loadsPower:
            return .black.opacity(0.2)
        }
    }

    var description: String {
        switch self {
        case .generationPower:
            return "Power generated by the solar panels"
        case .feedinPower:
            return "Power being sent to the grid"
        case .batChargePower:
            return "Power charging the battery"
        case .batDischargePower:
            return "Power discharging from the battery"
        case .gridConsumptionPower:
            return "Power coming from the grid"
        case .loadsPower:
            return "Loads power"
        }
    }
}

enum VariableType: String, RawRepresentable {
    case feedinPower
    case generationPower
    case gridConsumptionPower
    case pvPower
    case loadsPower
    case chargeEnergyToTal
    case batChargePower

    var rawTitle: String {
        return rawValue
    }

    var reportTitle: String {
        switch self {
        case .feedinPower:
            return "feedin"
        case .generationPower:
            return "generation"
        case .gridConsumptionPower:
            return "gridConsumption"
        case .chargeEnergyToTal:
            return "chargeEnergyToTal"
        case .pvPower:
            return "pvPower"
        case .loadsPower:
            return "loads"
        case .batChargePower:
            return "batChargePower"
        }
    }

    var description: String {
        switch self {
        case .feedinPower:
            return "Power being sent to the grid"
        case .generationPower:
            fallthrough
        case .loadsPower:
            return "Solar / battery power coming through the inverter"
        case .gridConsumptionPower:
            return "Power coming from the grid"
        case .chargeEnergyToTal:
            return "Power charging the battery"
        case .pvPower:
            return "Power generated by the solar panels"
        case .batChargePower:
            return "Power charging the battery"
        }
    }

    var title: String {
        switch self {
        case .feedinPower:
            return "Exported to grid"
        case .generationPower:
            fallthrough
        case .loadsPower:
            return "Generation Power"
        case .gridConsumptionPower:
            return "Imported from grid"
        case .chargeEnergyToTal:
            return "Battery Charge Power"
        case .pvPower:
            return "Solar Power"
        case .batChargePower:
            return "Power charging the battery"
        }
    }

    var colour: Color {
        switch self {
        case .feedinPower:
            return .blue.opacity(0.8)
        case .batChargePower:
            fallthrough
        case .generationPower:
            fallthrough
        case .loadsPower:
            return .mint.opacity(0.8)
        case .gridConsumptionPower:
            return .red.opacity(0.8)
        case .chargeEnergyToTal:
            return .green.opacity(0.8)
        case .pvPower:
            return .yellow.opacity(0.8)
        }
    }

    init?(fromReport variable: String) {
        switch variable {
        case "feedin":
            self = VariableType.feedinPower
        case "feedinPower":
            self = VariableType.feedinPower
        case "generation":
            self = VariableType.generationPower
        case "generationPower":
            self = VariableType.generationPower
        case "gridConsumption":
            self = VariableType.gridConsumptionPower
        case "gridConsumptionPower":
            self = VariableType.gridConsumptionPower
        case "pvPower":
            self = VariableType.pvPower
        case "chargeEnergyToTal":
            self = VariableType.chargeEnergyToTal
        case "batChargePower":
            self = VariableType.batChargePower
        default:
            return nil
        }
    }
}
